jar_library(
		name='junit',
		jars=[
			jar('junit', 'junit', '4.12')
		],
		scope='forced'
)

jar_library(
		name='scalatest',
		jars=[
			scala_jar('org.scalatest', 'scalatest', '2.2.4')
		]
)

jar_library(
    name='scala-xml',
    jars=[
      scala_jar('org.scala-lang.modules', 'scala-xml', '1.0.6')
    ]
)
